name: Build documentation

on:
  push:
    branches:
      - main
      - doc-builder*
      - v*-release
      - develop

jobs:
   build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
    with:
      commit_sha: ${{ github.sha }}
      package: evaluate
